# Generated by Django 5.1.7 on 2026-07-07 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('employee_name', models.CharField(blank=True, default='', max_length=255)),
                ('attendance_date', models.DateField(db_index=True)),
                ('requested_check_in', models.DateTimeField(blank=True, null=True)),
                ('requested_check_out', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('reviewer', models.CharField(blank=True, default='', max_length=255)),
                ('reviewer_note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attendance_corrections',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GeoFence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_meters', models.IntegerField(default=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attendance_geofences',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField(default='09:00')),
                ('end_time', models.TimeField(default='18:00')),
                ('break_minutes', models.IntegerField(default=60)),
                ('grace_minutes', models.IntegerField(default=15)),
                ('is_flexible', models.BooleanField(default=False)),
                ('flex_hours_per_day', models.FloatField(default=8.0)),
                ('overtime_after_minutes', models.IntegerField(default=540)),
                ('is_night_shift', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attendance_shifts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WfhRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('employee_name', models.CharField(blank=True, default='', max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('days', models.IntegerField(default=1)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('approver', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wfh_requests',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='geo_fence_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='break_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='early_exit_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='geo_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='is_wfh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='late_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='overtime_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='shift_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.shift')),
            ],
            options={
                'db_table': 'shift_assignments',
                'ordering': ['-effective_from'],
            },
        ),
    ]
