# Generated by Django 5.1.15 on 2026-07-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='priority',
            field=models.CharField(default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
