# Generated by Django 5.1.7 on 2026-07-08 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_status_priority_to_jobpost'),
        ('api', '0015_attendance_advanced_features'),
    ]

    operations = [
    ]
