# Generated by Django 5.1.7 on 2026-07-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20260708_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='status_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(default='Active', max_length=40),
        ),
    ]
