# Generated by Django 5.1.7 on 2026-07-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_consolidate_action_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewlink',
            name='notes_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewlink',
            name='notes_updated_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='interviewlink',
            name='notes_updated_by_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
