# Generated by Django 5.1.7 on 2026-07-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_interviewlink_notes_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFormTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('schema', models.JSONField(blank=True, default=list)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_form_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MasterDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('options', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'master_data_sets',
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='jobpost',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
