# Generated by Django 5.1.7 on 2026-07-14 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_attendance_remote_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=120)),
                ('last_name', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('client', models.CharField(blank=True, default='', max_length=255)),
                ('vendor', models.CharField(blank=True, default='', max_length=255)),
                ('recruiter', models.CharField(blank=True, default='', max_length=255)),
                ('job_title', models.CharField(blank=True, default='', max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='Draft', max_length=32)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.ForeignKey(blank=True, db_column='interview_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_candidates', to='api.interviewlink')),
            ],
            options={
                'db_table': 'onboarding_candidates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, default='', max_length=120)),
                ('actor_email', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('actor_name', models.CharField(blank=True, default='', max_length=255)),
                ('comments', models.TextField(blank=True, default='')),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(db_column='candidate_id', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='api.onboardingcandidate')),
            ],
            options={
                'db_table': 'onboarding_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagerApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('comments', models.TextField(blank=True, default='')),
                ('approver', models.CharField(blank=True, default='', max_length=255)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(db_column='candidate_id', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='api.onboardingcandidate')),
            ],
            options={
                'db_table': 'manager_approvals',
                'ordering': ['-acted_at'],
            },
        ),
        migrations.CreateModel(
            name='ItAssetAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_source', models.CharField(db_index=True, default='Eversoft', max_length=20)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('assets', models.JSONField(blank=True, default=list)),
                ('asset_id', models.CharField(blank=True, default='', max_length=120)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='Assigned', max_length=20)),
                ('allocated_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(db_column='candidate_id', on_delete=django.db.models.deletion.CASCADE, related_name='asset_allocations', to='api.onboardingcandidate')),
            ],
            options={
                'db_table': 'it_asset_allocations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HrVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn_verified', models.BooleanField(default=False)),
                ('driver_license_verified', models.BooleanField(default=False)),
                ('state_id_verified', models.BooleanField(default=False)),
                ('visa_verified', models.BooleanField(default=False)),
                ('i94_verified', models.BooleanField(default=False)),
                ('status', models.CharField(db_index=True, default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('verified_by', models.CharField(blank=True, default='', max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(db_column='candidate_id', on_delete=django.db.models.deletion.CASCADE, related_name='hr_verification', to='api.onboardingcandidate')),
            ],
            options={
                'db_table': 'hr_verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(db_index=True, max_length=40)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_mime', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.IntegerField(default=0)),
                ('file_data', models.TextField(blank=True, default='')),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(db_column='candidate_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.onboardingcandidate')),
            ],
            options={
                'db_table': 'candidate_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, default='', max_length=255)),
                ('account_number', models.CharField(blank=True, default='', max_length=64)),
                ('routing_number', models.CharField(blank=True, default='', max_length=64)),
                ('tax_state', models.CharField(blank=True, default='', max_length=64)),
                ('direct_deposit', models.BooleanField(default=False)),
                ('status', models.CharField(db_index=True, default='Pending', max_length=20)),
                ('completed_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(db_column='candidate_id', on_delete=django.db.models.deletion.CASCADE, related_name='payroll', to='api.onboardingcandidate')),
            ],
            options={
                'db_table': 'payroll_information',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('status', models.CharField(db_index=True, default='Pending', max_length=32)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('receipt_number', models.CharField(blank=True, default='', max_length=120)),
                ('sponsorship_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(db_column='candidate_id', on_delete=django.db.models.deletion.CASCADE, related_name='work_authorization', to='api.onboardingcandidate')),
            ],
            options={
                'db_table': 'work_authorizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkAuthorizationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_authorization', models.OneToOneField(db_column='work_authorization_id', on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='api.workauthorization')),
            ],
            options={
                'db_table': 'work_authorization_details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(db_index=True, max_length=40)),
                ('status', models.CharField(db_index=True, default='Pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(db_column='candidate_id', on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='api.onboardingcandidate')),
            ],
            options={
                'db_table': 'onboarding_status',
                'ordering': ['id'],
                'unique_together': {('candidate', 'stage')},
            },
        ),
    ]
