# Generated by Django 5.1.7 on 2026-07-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_onboarding_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingSetting',
            fields=[
                ('key', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'onboarding_settings',
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='onboardingcandidate',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
