# Generated by Django 5.1.7 on 2026-07-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_onboardingsetting_onboardingcandidate_custom_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingFormTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('schema', models.JSONField(blank=True, default=list)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'onboarding_form_templates',
                'ordering': ['name'],
            },
        ),
    ]
