# Generated by Django 5.1.7 on 2026-07-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_onboardingformtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedocument',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidatedocument',
            name='label',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='hrverification',
            name='custom_verified',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workauthorization',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
