# Generated by Django 5.1.7 on 2026-07-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_payroll_electronic_filling'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumescore',
            name='file_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumescore',
            name='file_mime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
