# Generated by Django 5.1.7 on 2026-07-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_resumescore_file_data_resumescore_file_mime'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumescore',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
