# Generated by Django 5.1.15 on 2026-07-30 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_candidate_profile_fields'),
        ('api', '0034_resumescore_content_hash'),
    ]

    operations = [
    ]
