# Generated by Django 5.1.15 on 2026-07-30 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_emailtemplate'),
        ('api', '0035_merge_20260730_0134'),
    ]

    operations = [
    ]
