# Generated by Django 5.1.15 on 2026-08-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_hrverification_passport_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrverification',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hrverification',
            name='employee_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='hrverification',
            name='report_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='hrverification',
            name='requested_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hrverification',
            name='vendor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hrverification',
            name='verification_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='hrverification',
            name='id',
            field=models.AutoField(db_column='verification_id', primary_key=True, serialize=False),
        ),
    ]
