# Generated by Django 5.1.15 on 2026-08-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_merge_0035_emailtemplate_0035_merge_20260730_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='location_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='location_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='location_reviewer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='location_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='overtime_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
