# Generated by Django 5.1.15 on 2026-08-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_employeeattendance_location_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='auto_checkout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='late_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
