# Generated by Django 5.1.7 on 2026-08-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_employeecompensation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkArrangement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('employee_name', models.CharField(blank=True, default='', max_length=255)),
                ('arrangement', models.CharField(default='onsite', max_length=20)),
                ('remote_weekdays', models.CharField(blank=True, default='', max_length=32)),
                ('remote_days_per_week', models.IntegerField(default=0)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'work_arrangements',
                'ordering': ['-effective_from', '-id'],
                'indexes': [models.Index(fields=['email', 'effective_from'], name='work_arrang_email_c8afa0_idx')],
            },
        ),
    ]
