# Generated by Django 5.1.7 on 2026-08-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_arrangement_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofence',
            name='captured_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geofence',
            name='owner_email',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='geofence',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geofence',
            name='reviewer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='geofence',
            name='status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
