# Generated by Django 5.1.7 on 2026-08-11 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_home_geofences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('key', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('lead_email', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='active', max_length=20)),
                ('last_item_number', models.IntegerField(default=0)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('goal', models.TextField(blank=True, default='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='api.project')),
            ],
            options={
                'db_table': 'project_cycles',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('state', models.CharField(db_index=True, default='todo', max_length=20)),
                ('priority', models.CharField(default='none', max_length=10)),
                ('assignee_email', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('reporter_email', models.CharField(blank=True, default='', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('estimate', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='api.cycle')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.workitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.project')),
            ],
            options={
                'db_table': 'work_items',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkItemActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.CharField(blank=True, default='', max_length=255)),
                ('field', models.CharField(max_length=40)),
                ('old_value', models.CharField(blank=True, default='', max_length=255)),
                ('new_value', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='api.workitem')),
            ],
            options={
                'db_table': 'work_item_activity',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkItemComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_email', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.workitem')),
            ],
            options={
                'db_table': 'work_item_comments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkItemLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('colour', models.CharField(default='#64748b', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='api.project')),
            ],
            options={
                'db_table': 'work_item_labels',
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='workitem',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='items', to='api.workitemlabel'),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(default='member', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.project')),
            ],
            options={
                'db_table': 'project_members',
                'ordering': ['email'],
                'unique_together': {('project', 'email')},
            },
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['project', 'state'], name='work_items_project_6f88bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workitem',
            unique_together={('project', 'number')},
        ),
    ]
