# Generated by Django 5.1.15 on 2026-08-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_chat_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('created_by', models.CharField(max_length=255)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('join_url', models.CharField(blank=True, default='', max_length=512)),
                ('attendees', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'chat_meetings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_email', models.CharField(max_length=255)),
                ('joined_at', models.DateTimeField()),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'chat_members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.CharField(max_length=255)),
                ('sender_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment_data', models.TextField(blank=True, null=True)),
                ('attachment_path', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_group', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('is_private', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'chat_rooms',
                'managed': False,
            },
        ),
    ]
