# Generated by Django on 2026-08-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_projects_module'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ChatRoom',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('room_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                        ('name', models.CharField(blank=True, max_length=255, null=True)),
                        ('room_type', models.CharField(default='direct', max_length=50)),
                        ('created_by', models.CharField(blank=True, default='', max_length=255)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'db_table': 'chat_rooms',
                        'ordering': ['-updated_at'],
                    },
                ),
                migrations.CreateModel(
                    name='ChatMessage',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('sender_email', models.CharField(db_index=True, max_length=255)),
                        ('content', models.TextField(blank=True, null=True)),
                        ('message_type', models.CharField(default='text', max_length=50)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatroom')),
                    ],
                    options={
                        'db_table': 'chat_messages',
                        'ordering': ['created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='ChatParticipant',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('email', models.CharField(max_length=255)),
                        ('joined_at', models.DateTimeField(auto_now_add=True)),
                        ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.chatroom')),
                    ],
                    options={
                        'db_table': 'chat_participants',
                        'ordering': ['joined_at'],
                        'unique_together': {('room', 'email')},
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS `chat_rooms` (
                        `id` INT AUTO_INCREMENT PRIMARY KEY,
                        `room_id` VARCHAR(128) UNIQUE NULL,
                        `name` VARCHAR(255) NULL,
                        `room_type` VARCHAR(50) DEFAULT 'direct',
                        `created_by` VARCHAR(255) NULL,
                        `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
                        `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

                    CREATE TABLE IF NOT EXISTS `chat_messages` (
                        `id` INT AUTO_INCREMENT PRIMARY KEY,
                        `room_id` INT NULL,
                        `sender_email` VARCHAR(255) NOT NULL,
                        `content` TEXT NULL,
                        `message_type` VARCHAR(50) DEFAULT 'text',
                        `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
                        KEY `idx_room_id` (`room_id`),
                        KEY `idx_sender_email` (`sender_email`)
                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

                    CREATE TABLE IF NOT EXISTS `chat_participants` (
                        `id` INT AUTO_INCREMENT PRIMARY KEY,
                        `room_id` INT NOT NULL,
                        `email` VARCHAR(255) NOT NULL,
                        `joined_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
                        UNIQUE KEY `idx_room_email` (`room_id`, `email`)
                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
                    """,
                    reverse_sql="""
                    DROP TABLE IF EXISTS `chat_participants`;
                    DROP TABLE IF EXISTS `chat_messages`;
                    DROP TABLE IF EXISTS `chat_rooms`;
                    """
                ),
            ]
        ),
    ]
