# Generated by Django 5.1.15 on 2026-08-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_chat_tables'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='workitem',
                    name='cycle',
                ),
                migrations.RemoveField(
                    model_name='projectmember',
                    name='project',
                ),
                migrations.RemoveField(
                    model_name='workitemlabel',
                    name='project',
                ),
                migrations.RemoveField(
                    model_name='workitem',
                    name='project',
                ),
                migrations.AlterUniqueTogether(
                    name='projectmember',
                    unique_together=None,
                ),
                migrations.AlterUniqueTogether(
                    name='workitem',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='workitem',
                    name='labels',
                ),
                migrations.RemoveField(
                    model_name='workitem',
                    name='parent',
                ),
                migrations.RemoveField(
                    model_name='workitemactivity',
                    name='work_item',
                ),
                migrations.RemoveField(
                    model_name='workitemcomment',
                    name='work_item',
                ),
                migrations.AlterUniqueTogether(
                    name='workitemlabel',
                    unique_together=None,
                ),
                migrations.AlterField(
                    model_name='chatmessage',
                    name='id',
                    field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='chatparticipant',
                    name='id',
                    field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='chatroom',
                    name='id',
                    field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.DeleteModel(
                    name='Cycle',
                ),
                migrations.DeleteModel(
                    name='ProjectMember',
                ),
                migrations.DeleteModel(
                    name='Project',
                ),
                migrations.DeleteModel(
                    name='WorkItemLabel',
                ),
                migrations.DeleteModel(
                    name='WorkItemActivity',
                ),
                migrations.DeleteModel(
                    name='WorkItem',
                ),
                migrations.DeleteModel(
                    name='WorkItemComment',
                ),
            ],
            database_operations=[]
        )
    ]
