# Generated by Django 5.1.7 on 2026-08-19 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_chat_pin_reply_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmeeting',
            options={'managed': False, 'ordering': ['scheduled_at']},
        ),
    ]
