# Generated by Django 5.1.15 on 2026-08-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_submission_view_all_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrverification',
            name='address_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrverification',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hrverification',
            name='criminal_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrverification',
            name='education_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrverification',
            name='employee_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='hrverification',
            name='employment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrverification',
            name='identity_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrverification',
            name='passport_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrverification',
            name='reference_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrverification',
            name='report_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='hrverification',
            name='requested_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hrverification',
            name='vendor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hrverification',
            name='verification_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='hrverification',
            name='id',
            field=models.AutoField(db_column='verification_id', primary_key=True, serialize=False),
        ),
    ]
