# Generated by Django 5.1.7 on 2026-08-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_hrverification_background_checks'),
        ('api', '0054_submission_view_all_permission'),
    ]

    operations = [
    ]
