# Generated by Django on 2026-08-24
import json
from django.db import migrations, models


def seed_and_backfill(apps, schema_editor):
    CompanyDetail = apps.get_model('api', 'CompanyDetail')
    AppUser = apps.get_model('api', 'AppUser')
    UserProfile = apps.get_model('api', 'UserProfile')

    comp = CompanyDetail.objects.first()
    if not comp:
        comp = CompanyDetail.objects.create(
            company_name='Eversoft Technologies',
            brand_name='Eversoft',
            legal_name='Eversoft Technologies Private Limited',
            website='https://eversoftit.com',
            contact_email='contact@eversoftit.com',
            phone='+91 98765 43210',
            industry='Information Technology & Services',
            country='India',
            timezone='Asia/Kolkata',
            currency='INR',
            date_format='DD/MM/YYYY',
            work_week=['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
            emp_id_prefix='EV-',
            emp_id_min_digits=4,
            emp_id_start_number=1,
            emp_id_suffix='',
            company_logo=''
        )

    prefix = comp.emp_id_prefix or 'EV-'
    digits = comp.emp_id_min_digits or 4
    start_num = comp.emp_id_start_number or 1
    suffix = comp.emp_id_suffix or ''

    counter = start_num
    for user in AppUser.objects.order_by('id'):
        if not user.employee_id:
            eid = f"{prefix}{str(counter).zfill(digits)}{suffix}"
            user.employee_id = eid
            user.save(update_fields=['employee_id'])
            if user.email:
                UserProfile.objects.filter(email=user.email, employee_id='').update(employee_id=eid)
            counter += 1

    for prof in UserProfile.objects.filter(employee_id='').order_by('id'):
        eid = f"{prefix}{str(counter).zfill(digits)}{suffix}"
        prof.employee_id = eid
        prof.save(update_fields=['employee_id'])
        counter += 1


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_chat_member_last_read_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Eversoft Technologies', max_length=255)),
                ('legal_name', models.CharField(blank=True, default='', max_length=255)),
                ('brand_name', models.CharField(blank=True, default='Eversoft', max_length=255)),
                ('company_logo', models.TextField(blank=True, default='')),
                ('website', models.CharField(blank=True, default='https://eversoftit.com', max_length=255)),
                ('contact_email', models.CharField(blank=True, default='contact@eversoftit.com', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('tax_id', models.CharField(blank=True, default='', max_length=100)),
                ('industry', models.CharField(blank=True, default='Information Technology', max_length=120)),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=20)),
                ('timezone', models.CharField(blank=True, default='Asia/Kolkata', max_length=100)),
                ('currency', models.CharField(blank=True, default='INR', max_length=10)),
                ('date_format', models.CharField(blank=True, default='DD/MM/YYYY', max_length=30)),
                ('work_week', models.JSONField(blank=True, default=list)),
                ('emp_id_prefix', models.CharField(blank=True, default='EV-', max_length=20)),
                ('emp_id_min_digits', models.IntegerField(default=4)),
                ('emp_id_start_number', models.IntegerField(default=1)),
                ('emp_id_suffix', models.CharField(blank=True, default='', max_length=20)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_details',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='employee_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.RunPython(seed_and_backfill, noop),
    ]
