# Generated by Django 5.1.15 on 2026-08-25 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_company_details_and_employee_id'),
        ('api', '0057_team_lead_role'),
    ]

    operations = [
    ]
