# Generated by Django 5.1.15 on 2026-09-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_attendance_location_punch'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('vendor_prime_vendor', models.CharField(blank=True, default='', max_length=255)),
                ('vendor_person_name', models.CharField(blank=True, default='', max_length=255)),
                ('vendor_email', models.CharField(blank=True, default='', max_length=255)),
                ('vendor_contact', models.CharField(blank=True, default='', max_length=60)),
                ('implementation_partner', models.CharField(blank=True, default='', max_length=255)),
                ('rate', models.CharField(blank=True, default='', max_length=60)),
                ('role_responsibilities', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Submitted', max_length=40)),
                ('follow_up_vendor', models.DateField(blank=True, null=True)),
                ('interview_schedule', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bench_submissions',
                'ordering': ['-id'],
            },
        ),
    ]
