# Generated by Django 5.1.15 on 2026-09-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_attendance_location_punch'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksubmission',
            name='file_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksubmission',
            name='file_mime',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='worksubmission',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
    ]
