# Generated by Django 5.1.15 on 2026-09-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_benchsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchSalesProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tech_stack', models.CharField(blank=True, default='', max_length=500)),
                ('experience', models.CharField(blank=True, default='', max_length=60)),
                ('certificates', models.TextField(blank=True, default='')),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('contact_no', models.CharField(blank=True, default='', max_length=60)),
                ('work_authorization', models.CharField(blank=True, default='', max_length=40)),
                ('resume_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('resume_file_mime', models.CharField(blank=True, default='', max_length=100)),
                ('resume_file_data', models.TextField(blank=True, default='')),
                ('dl_state_id_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('dl_state_id_file_mime', models.CharField(blank=True, default='', max_length=100)),
                ('dl_state_id_file_data', models.TextField(blank=True, default='')),
                ('i94_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('i94_file_mime', models.CharField(blank=True, default='', max_length=100)),
                ('i94_file_data', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bench_sales_profiles',
                'ordering': ['-id'],
            },
        ),
    ]
