# Generated by Django 5.1.15 on 2026-09-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_worksubmission_file_data_worksubmission_file_mime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksubmission',
            name='review_file_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksubmission',
            name='review_file_mime',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='worksubmission',
            name='review_file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='worksubmission',
            name='review_file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worksubmission',
            name='reviewer_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksubmission',
            name='reviewer_note_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksubmission',
            name='reviewer_note_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
