# Generated by Django 5.1.15 on 2026-09-04 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_ai_resume_scoring_and_interview_eval'),
        ('api', '0062_worksubmission_review_file_data_and_more'),
    ]

    operations = [
    ]
