# Generated by Django 5.1.15 on 2026-09-07 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_benchsalesprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benchsalesprofile',
            name='certificates',
        ),
        migrations.CreateModel(
            name='BenchSalesCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_mime', models.CharField(blank=True, default='', max_length=100)),
                ('file_data', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_files', to='api.benchsalesprofile')),
            ],
            options={
                'db_table': 'bench_sales_certificates',
                'ordering': ['id'],
            },
        ),
    ]
