# Generated by Django 5.1.7 on 2026-09-07 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_merge_20260904_2247'),
        ('api', '0064_task_action_permissions'),
    ]

    operations = [
    ]
