# Generated by Django 5.1.15 on 2026-09-10 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_remove_benchsalesprofile_certificates_and_more'),
        ('api', '0065_merge_20260907_1823'),
    ]

    operations = [
    ]
